# Generated by Django 4.2.7 on 2024-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cityservices", "0002_busroute_geojson"),
    ]

    operations = [
        migrations.CreateModel(
            name="DublinBikeStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("bike_stands", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
