# Generated by Django 4.2.7 on 2024-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cityservices", "0003_sa_energy_consumption"),
        ("cityservices", "0004_rename_dublinbikestations_dublinbikestation"),
    ]

    operations = []
