# Generated by Django 5.0.1 on 2024-04-11 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityservices', '0005_merge_20240313_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublinbikestation',
            name='available_bikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dublinbikestation',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dublinbikestation',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dublinbikestation',
            name='usage_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
