# Generated by Django 4.2.9 on 2024-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SA_energy_consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SA_code', models.IntegerField()),
                ('Energy_use', models.IntegerField()),
                ('Energy_cost', models.IntegerField()),
                ('Total_Floor_Area', models.IntegerField()),
                ('Small_Area_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
