name: Tests

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      python-version: 3.9

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ python-version }}
    - name: Install Dependencies
      run: |
        cd Backend
        python3 -m pip3 install --upgrade pip
        pip3 install -r requirements.txt
      env:
        DJANGO_SETTINGS_MODULE: Backend.backend.settings
    - name: Running Tests
      run: |
        python3 manage.py test
